repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=127
          - --max-complexity=10
          - --ignore=E501,W503
